market_watch_task:
  description: >
    Monitor the market news for sector {sector}
  expected_output: >
    A list of 3 most newsworthy companies in sector {sector}
  agent: market_watcher


analysis_task:
  description: >
    Analyze the research findings on the 3 companies and pick the one that has the most potential for investigation for an analysis
    Your report should:
    1. Begin with an executive summary
    2. Select one of the 3 companies for further analysis for investment
    3. Give precise reasons for selecting this company, and whether it's worth investigating for a buy or sell, noting that this should not be used for trading decisions
    4. Mention the other 2 companies that were considered but not selected
    5. Be formatted in a professional, easy-to-read style with clear headings
  expected_output: >
    A polished, professional report on that presents the research
    findings with added analysis and insights. The report should be well-structured
    with an executive summary, main sections, and conclusion.
  agent: analyst
  output_file: output/report.md
